// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAOa2sqDucLhC_e0jgd-5LjgGKexAu7-0',
    appId: '1:524557077143:android:7bbe5b9541da580a1837d2',
    messagingSenderId: '524557077143',
    projectId: 'toda-mart',
    storageBucket: 'toda-mart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIDEZ9Pm8isew1Zv3szhbwciHH7-I42ps',
    appId: '1:524557077143:ios:cf3eaa7cfb9fbd871837d2',
    messagingSenderId: '524557077143',
    projectId: 'toda-mart',
    storageBucket: 'toda-mart.firebasestorage.app',
    iosBundleId: 'com.example.todaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIDEZ9Pm8isew1Zv3szhbwciHH7-I42ps',
    appId: '1:524557077143:ios:cf3eaa7cfb9fbd871837d2',
    messagingSenderId: '524557077143',
    projectId: 'toda-mart',
    storageBucket: 'toda-mart.firebasestorage.app',
    iosBundleId: 'com.example.todaApp',
  );
}
